In [3]:
import numpy as np

In [6]:
arr_1d = np.array([1,2,3,4,5])
arr_1d

array([1, 2, 3, 4, 5])

In [8]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
zeros_arr = np.zeros((3,3))
zeros_arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
ones_arr = np.ones((2,3))
ones_arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
identity_mat = np.eye(3)
identity_mat

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Arithmetic Operations in Numpy

In [21]:
array_a = np.array([1,2,3])
array_b = np.array([4,5,6])

In [23]:
res_add = array_a + array_b
res_mul = array_a * array_b
res_add

array([5, 7, 9])

In [24]:
res_mul

array([ 4, 10, 18])

# MATRIX OPERATIONS

In [25]:
mat_a = np.array([[1,2],[3,4]])
mat_b = np.array([[5,6],[7,8]])

In [26]:
result_mat = np.dot(mat_a, mat_b)
result_mat

array([[19, 22],
       [43, 50]])

In [29]:
result_mat[0][0] = 20
result_mat

array([[20, 22],
       [43, 50]])

# INDEXING & SLICING

In [30]:
arr = np.array([1, 2, 3, 4, 5])

In [31]:
print(arr[2])

3


In [34]:
print(arr[-1]) 

5


In [35]:
print(arr[1:]) 

[2 3 4 5]


In [36]:
print(arr[:-2]) 

[1 2 3]


# STATISTICAL OPERATIONS

In [41]:
arr = np.array([1, 2, 3, 4, 5])
mean_val = np.mean(arr)
mean_val

3.0

In [43]:
median_val = np.median(arr)
median_val

3.0

In [44]:
std_dev = np.std(arr)
std_dev

1.4142135623730951

## ARRAY RESHAPE

In [46]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr.shape

(2, 3)


reshaoed_arr = arr.reshape(3,2)
reshaoed_arr

In [47]:
arr = np.arange(1,26)
arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [49]:
arr = np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [50]:
arr.sum()

325

In [51]:
arr.mean()

13.0

In [52]:
import time

# py list
start_time = time.time()
python_list = list(range(10**6))
python_list = [x**2 for x in python_list]
end_time = time.time()
print("PYTHON LIST EXECUTION TIME ", end_time-start_time)

# numoy list
start_time = time.time()
numpy_array = np.arange(10**6)
numpy_array = numpy_array **2
end_time = time.time()
print("PYTHON NUMPY  EXECUTION TIME ", end_time-start_time)

PYTHON LIST EXECUTION TIME  0.44998860359191895
PYTHON NUMPY  EXECUTION TIME  0.01202082633972168


# DEEP VS SHALLOW COPY

In [56]:
original_array = np.array([1, 2, 3])
shallow_copy = original_array
shallow_copy[0] = 10
shallow_copy

array([10,  2,  3])

In [57]:
original_array

array([10,  2,  3])

In [61]:
original_array = np.array([1, 2, 3])
deep_copy = np.copy(original_array)
deep_copy[0] = 100
deep_copy

array([100,   2,   3])

In [62]:
original_array

array([1, 2, 3])

In [63]:
np.random.randn(1)

array([-1.79151192])